# Generated by Django 2.0.7 on 2018-07-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180720_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='ddd', max_length=255),
            preserve_default=False,
        ),
    ]
